---
- name: Download k0s binary k0s-{{ k0s_version }}-arm64
  ansible.builtin.get_url:
    url: https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-arm64 
    dest: /tmp/k0s-{{ k0s_version }}-arm64

- name: Install k0s binary in /usr/local/bin
  become: true
  ansible.builtin.command: install /tmp/k0s-{{ k0s_version }}-arm64 /usr/local/bin/k0s

