---
- name: Install nfs-kernel-server package
  become: true
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Disable statd service
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/nfs-common
    regexp: '^NEED_STATD='
    line: 'NEED_STATD="no"'

- name: Enable idmapd service
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/nfs-common
    regexp: '^NEED_IDMAPD='
    line: 'NEED_IDMAPD="yes"'

- name: Disbale NFS v3 and v4 for nfsd
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/nfs-kernel-server
    line: 'RPCNFSDOPTS="-N 2 -N 3"'
  notify: Restart the nfs-kernel-server service

- name: Disbale NFS v3 and v4 for mountd
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/nfs-kernel-server
    regexp: '^RPCMOUNTDOPTS='
    line: 'RPCMOUNTDOPTS="--manage-gids -N 2 -N 3"'
  notify: Restart the nfs-kernel-server service

- name: Configure /etc/idmapd.conf file
  become: true
  ansible.builtin.lineinfile:
    path: /etc/idmapd.conf
    regexp: '^#\sDomain'
    line: 'Domain = localdomain'

- name: Mask rpcbind.service
  become: true
  ansible.builtin.systemd_service:
    name: rpcbind.service
    masked: true

- name: Mask rpcbind.socket
  become: true
  ansible.builtin.systemd_service:
    name: rpcbind.socket
    masked: true

- name: Create the /srv/nfs directory
  become: true
  ansible.builtin.file:
    path: /srv/nfs
    owner: root
    group: root
    mode: '0755'
    state: directory 

- name: Mount /mnt/backup directory to /srv/nfs
  become: true
  ansible.posix.mount:
    path: /srv/nfs/backup
    src: /mnt/backup
    opts: bind
    state: mounted
    fstype: none

- name: Mount /mnt/home directory to /srv/nfs
  become: true
  ansible.posix.mount:
    path: /srv/nfs/home
    src: /mnt/home
    opts: bind
    state: mounted
    fstype: none

- name: Mount /mnt/volume directory to /srv/nfs
  become: true
  ansible.posix.mount:
    path: /srv/nfs/volume
    src: /mnt/volume
    opts: bind
    state: mounted
    fstype: none

- name: Configure nfs4_disable_idmapping option
  become: true
  ansible.builtin.template:
    src: nfsd.j2
    dest: /etc/modprobe.d/nfsd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart the nfs-kernel-server service

- name: Configure /etc/exports file
  become: true
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: Restart the nfs-kernel-server service

