---
- name: Install cgroup-tools package
  become: true
  ansible.builtin.package:
    name: cgroup-tools
    state: present

- name: Install cgroupfs-mount package
  become: true
  ansible.builtin.package:
    name: cgroupfs-mount
    state: present

- name: Activate cgroup support
  become: true
  ansible.builtin.lineinfile:
    path: /boot/cmdline.txt
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
    backrefs: true
  notify: Reboot

- name: Load overlay module
  become: true
  community.general.modprobe:
    name: overlay
    persistent: present
    state: present

- name: Load nf_conntrack module
  become: true
  community.general.modprobe:
    name: nf_conntrack
    persistent: present
    state: present

- name: Load br_netfilter module
  become: true
  community.general.modprobe:
    name: br_netfilter
    persistent: present
    state: present

- name: Flush handlers
  meta: flush_handlers

