---
- name: Install nfs-kernel-server package
  become: true
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Create the /srv/nfs directory
  become: true
  ansible.builtin.file:
    path: /srv/nfs
    owner: root
    group: root
    mode: '0755'
    state: directory 

- name: Mount /mnt/home directory to /srv/nfs
  become: true
  ansible.posix.mount:
    path: /srv/nfs/home
    src: /mnt/home
    opts: bind
    state: mounted
    fstype: none

- name: Mount /mnt/volume directory to /srv/nfs
  become: true
  ansible.posix.mount:
    path: /srv/nfs/volume
    src: /mnt/volume
    opts: bind
    state: mounted
    fstype: none

- name: Configure /etc/exports file
  become: true
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: Restart the nfs-kernel-server service

