---
- name: Install nfs-kernel-server package
  become: true
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Create the /srv/nfs directory
  become: true
  ansible.builtin.file:
    path: /srv/nfs
    owner: root
    group: root
    mode: '0755'
    state: directory 

- name: Mount /mnt/btrfs/appdata directory to /srv/nfss
  become: true
  ansible.posix.mount:
    path: /srv/nfs/appdata
    src: /mnt/btrfs/appdata
    opts: bind
    state: mounted
    fstype: none

- name: Mount /mnt/btrfs/home directory to /srv/nfs
  become: true
  ansible.posix.mount:
    path: /srv/nfs/home
    src: /mnt/btrfs/home
    opts: bind
    state: mounted
    fstype: none

- name: Configure /etc/exports file
  become: true
  ansible.builtin.template:
    src: exports.j2
    dest: /etc/exports
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Restart the nfs-kernel-server service
  become: true
  ansible.builtin.service:
    name: nfs-kernel-server
    state: restarted
    enabled: true

