---
- name: Create /var/lib/k0s directory
  become: true
  ansible.builtin.file:
    path: /var/lib/k0s
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: Create the token file for the worker
  become: true
  ansible.builtin.copy:
    content: "{{ hostvars[groups['controller'][0]]['token'] }}"
    dest: /var/lib/k0s/token
    owner: root
    group: root
    mode: '0600'

- name: Install the k0sworker service
  become: true
  ansible.builtin.command: k0s install worker --token-file /var/lib/k0s/token

- name: Start the k0sworker service
  become: true
  ansible.builtin.systemd_service:
    name: k0sworker
    state: started
    enabled: true

