---
- name: Install the k0scontroller service
  become: true
  ansible.builtin.command: k0s install controller --enable-worker

- name: Start the k0scontroller service
  become: true
  ansible.builtin.systemd_service:
    name: k0scontroller
    state: started
    enabled: true

- name: Wait for k8s apiserver
  ansible.builtin.wait_for:
    host: localhost
    port: 6443
    delay: 15
    timeout: 180

- name: Create join token with worker role
  become: true
  ansible.builtin.command: k0s token create --role worker
  register: token

- name: Store worker join token
  ansible.builtin.set_fact:
    token: "{{ token.stdout }}"
    cacheable: yes

- name: Get the kubeconfig for the Admin user
  become: true
  ansible.builtin.command: k0s kubeconfig admin
  register: kubeconfig

- name: Creat the ~/.kube directory
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.kube"
    state: directory

- name: Create the kubeconfig file locally
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ kubeconfig.stdout }}"
    dest: "{{ lookup('env', 'HOME') }}/.kube/config"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0644'

