---
- name: Install lm-sensors package
  ansible.builtin.apt:
    name: lm-sensors
    state: present
    update_cache: true

- name: Load the drivetemp kernel module
  community.general.modprobe:
    name: drivetemp
    state: present
    persistent: present
  when: ansible_hostname == "raspberrypi-03"

- name: Detect and generate a list of kernel modules
  ansible.builtin.command: sensors-detect --auto
