---
- name: Prepare for k3s installation
  hosts: k3s_cluster
  become: true
  roles:
    - role: k3s/prereq

- name: Setup K3s server
  hosts: server
  become: true
  roles:
    - role: k3s/server

- name: Setup K3s agent
  hosts: agent
  become: true
  roles:
    - role: k3s/agent
