---
- name: Configure node
  hosts: all
  become: true
  roles:
    - role: iscsi/initiator
    - role: lm-sensors
    - role: log2ram
    - role: sysstat

- name: Configure storage node
  hosts: raspberrypi-03
  become: true
  roles:
    - role: iscsi/target
    - role: zfs
